### ISSUE TITLE
查看数字签名时显示无效，版权处空白

### ISSUE THREAD

**Issue by yinsel** [langsasec/Sign-Sacker#1]
我提取的QQ的签名，复制签名后查看显示无效，不知是否正常：

![image](https://github.com/langsasec/Sign-Sacker/assets/91541985/cf49cde0-83d7-4c14-b5a6-30e851419538)

没有版权信息：

![image](https://github.com/langsasec/Sign-Sacker/assets/91541985/72d208d2-1035-4ad2-a8a4-04a6ff022b9b)

**Comment by langsasec** [comment]
没错，抢来的签名本就是这样

**Comment by yinsel** [comment]
ok
